version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4
          environment:
            USER_NAME: kisakov
            USER_EMAIL: isakov90@gmail.com
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "2b:77:eb:0c:4b:cb:52:a8:76:22:6a:9e:ef:47:03:94"
      - run:
          name: setup
          command: ./bin/setup
      - run:
          name: jekyll build
          command: bundle exec jekyll build
      - run:
          name: deploy
          command: ./bin/deploy